version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dvc-ai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - dvc-ai-network

volumes:
  redis_data:
    driver: local

networks:
  dvc-ai-network:
    driver: bridge
